"""Make a small synthetic recording, so the UI can be driven with no instrument.

    python tools/make_demo_recording.py demo

Writes `demo.raw` and `demo_meta.json`. The signal is not physiological and
is not meant to be: it exists so the window has packets to move, gaps to
report and a clock to advance. Anything read off it as science would be read
off a sine wave and some noise.
"""

import json
import sys
from pathlib import Path

import numpy as np

FRAME_RATE_HZ = 18557.720703125
N_CHANNELS = 64          # not 4096: a demo file should not be 150 MB/s
SECONDS = 20.0


def main(argv=None) -> int:
    argv = list(sys.argv[1:] if argv is None else argv)
    stem = Path(argv[0]) if argv else Path("demo")
    n_frames = int(FRAME_RATE_HZ * SECONDS)

    rng = np.random.default_rng(20260817)
    t = np.arange(n_frames) / FRAME_RATE_HZ
    # A slow drift plus noise, offset into the middle of a 12-bit range.
    base = 2048 + 300 * np.sin(2 * np.pi * 3.0 * t)
    data = (base[:, None] + rng.normal(0, 40, size=(n_frames, N_CHANNELS)))
    np.clip(data, 0, 4095, out=data)
    data.astype(np.uint16).tofile(stem.with_suffix(".raw"))

    meta = {
        "frame_rate_hz": FRAME_RATE_HZ,
        "total_channels": N_CHANNELS,
        "ch_sample_byte_size": 2,
        "bit_depth": 12,
        "adc_counts_to_value": 2.0146520146520146,
        "offset": -4125.0,
        "min_digital_value": 0,
        "max_digital_value": 4095,
        "note": ("Synthetic. Generated by tools/make_demo_recording.py for "
                 "driving the UI without an instrument. Not real signal."),
    }
    meta_path = stem.with_name(stem.stem + "_meta.json")
    meta_path.write_text(json.dumps(meta, indent=2), encoding="utf-8")

    size_mb = stem.with_suffix(".raw").stat().st_size / 1e6
    print(f"{stem.with_suffix('.raw')}  ({size_mb:.1f} MB, {n_frames:,} frames, "
          f"{N_CHANNELS} channels, {SECONDS:g} s)")
    print(f"{meta_path}")
    print()
    print("Drive the window with it:")
    print(f"  python -m biocam.ui --replay {stem.with_suffix('.raw')} "
          f"--meta {meta_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
